name: Build/Test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      part:
        required: false
        default: ''

jobs:
  build:
    name: Build the library and run tests
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-filelock python3-pytest python3-rbd python3-rados

      - name: Build and install library
        run: |
          sudo python3 setup.py install

      - name: Run unit tests
        run: |
          pytest-3 .

      - name: Run functional tests (file backend)
        run: |
          python3 scripts/func_test.py file /tmp/tosc_test

      - name: Run functional tests (Ceph backend)
        run: |
          # Install and setup LXD
          sudo snap install lxd --channel=5.21/stable
          sudo chown root:lxd /var/snap/lxd/common/lxd/unix.socket
          sudo usermod -aG lxd $USER
          newgrp lxd
          sudo lxd init --auto

          # Launch the containers.
          for name in node1 node2 node3; do
            lxc launch ubuntu:24.04 $name
          done

          sleep 30

          # Install Microceph in the containers
          for name in node1 node2 node3; do
            lxc exec $name -- sudo snap install microceph
          done

          # Bootstrap the cluster and add the nodes
          lxc exec node1 -- sudo microceph cluster bootstrap
          TOKEN=$(lxc exec node1 -- sudo microceph cluster add node2)
          lxc exec node2 -- sudo microceph cluster join $TOKEN

          TOKEN=$(lxc exec node1 -- sudo microceph cluster add node3)
          lxc exec node3 -- sudo microceph cluster join $TOKEN

          # Add the OSDs
          for name in node1 node2 node3; do
            lxc exec $name -- sudo microceph disk add loop,1G,1
          done

          # Create the pool and image
          lxc exec node1 -- sudo microceph.ceph osd pool create test-pool
          lxc exec node1 -- sudo microceph.rbd pool init test-pool
          lxc exec node1 -- sudo microceph.rbd create --size 1024 test-pool/test-image

          # Get the monitor IP's
          MONS=$(lxc exec node3 -- sudo cat /var/snap/microceph/current/conf/ceph.conf | grep "mon host" | cut -d '=' -f2 | xargs)
          # Get the admin key
          KEY=$(lxc exec node1 -- sudo microceph.ceph auth print-key client.admin)

          # Finally, run the tests
          python3 scripts/func_test.py ceph admin $KEY $MONS test-pool test-image object
