name: Build/Test

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      part:
        required: false
        default: ''

jobs:
  build:
    name: Build the library and run tests
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-filelock python3-pytest python3-rbd python3-rados

      - name: Build and install library
        run: |
          sudo python3 setup.py install

      - name: Run unit tests
        run: |
          pytest-3 .

      - name: Run functional tests (file backend)
        run: |
          python3 scripts/func_test.py file /tmp/tosc_test

      - name: Run functional tests (Ceph backend)
        run: |
          # Install microceph
          sudo snap install microceph
          sudo snap refresh microceph

          # Bootstrap single node cluster
          sudo microceph cluster bootstrap

          # Add some storage
          sudo microceph disk add loop,1G,3

          # Create and initialize the pool
          sudo microceph.ceph osd pool create test-pool
          sudo microceph.rbd pool init test-pool

          # Get the monitor IP and admin key.
          MON=$(sudo cat /var/snap/microceph/current/conf/ceph.conf | grep "mon host" | cut -d '=' -f2 | xargs)
          KEY=$(sudo microceph.ceph auth print-key client.admin)

          # Finally, run the tests
          python3 scripts/func_test.py ceph admin $KEY $MON test-pool object
